### ISSUE TITLE
Use streams2?

### ISSUE THREAD

**Issue by feross** [maxogden/filereader-stream#5]
I'm not super familiar with how to work with old streams. This module doesn't seem to emit `data` events, which all streams should do. Listening for the `readable` event obviously doesn't work because that's streams2 only. It seems like `pipe` is the only thing that will work.

Would you accept a PR that ported this to use streams2?

**Comment by adius** [comment]
Yeah, this module is fundamentally flawed. You should write a warning in the readme and redirect to DamonOehlman/filestream

**Comment by adius** [comment]
Why are you closing this? Even without a comment. This is not a stream. It's just an event-emitter which happens to implement a pipe method. You should inform potential users about this!

**Comment by konklone** [comment]
Dude's under no obligation to do anything. It's an open source project, and a small one. Spend your energy making things.
